include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/**/*.freezed.dart
    - lib/src/**/*.g.dart
  errors:
    invalid_annotation_target: ignore
    # Should be removed after the following issue is fixed: https://github.com/rrousselGit/freezed/issues/1204
    unnecessary_non_null_assertion: ignore

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
