include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/**/*.freezed.dart
    - lib/src/**/*.g.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
